env:
  browser: true
  es2021: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - standard
  - 'plugin:jsx-a11y/recommended'
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - 'jsx-a11y'
rules:
  'no-use-before-define': 'off'
  '@typescript-eslint/no-use-before-define':
    - 'error'
  'no-useless-constructor': 'off'
  '@typescript-eslint/no-useless-constructor':
    - 'error'
  'no-undef': 'off'
settings:
  react:
    version: detect
globals: { 'JSX': 'readonly' }
